spryk: method
description: "Adds a method to the *module*BusinessFactory."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    subDirectory:
        inherit: true
        isOptional: true

    className:
        inherit: true

    interfaceName:
        inherit: true
        isOptional: true

    factoryMethod:
        callbackOnly: true
        callback: ZedBusinessFactoryMethodNameCallback

    dependencyMethods:
        isMultiple: true
        isOptional: true

    template:
        value: Zed/Business/MethodBusinessFactory.php.twig

    target:
        value: "{{ organization }}\\Zed\\{{ module }}\\Business\\{{ module }}BusinessFactory"

preSpryks:
    - AddZedBusinessFactory

postSpryks:
    - AddZedBusinessFactoryMethod:
          arguments:
              factoryMethod:
                  value: "create{{ domainEntity }}IdentifierBuilder"
              className:
                  value: "{{ domainEntity }}IdentifierBuilder"
              interfaceName:
                  value: "\\{{ organization }}\\Zed\\{{ module }}\\Business\\{{ domainEntity }}\\Identifier\\{{ domainEntity }}IdentifierInterface"
              subDirectory:
                  value: "{{ domainEntity }}/Identifier"
    - AddZedBusinessFactoryMethod:
          arguments:
              factoryMethod:
                  value: "create{{ domainEntity }}CreateValidator"
              className:
                  value: "{{ domainEntity }}Validator"
              interfaceName:
                  value: "\\{{ organization }}\\Zed\\{{ module }}\\Business\\{{ domainEntity }}\\Validator\\{{ domainEntity }}ValidatorInterface"
              subDirectory:
                  value: "{{ domainEntity }}/Validator"
              dependencyMethods:
                  value:
                      - "get{{ domainEntity }}IdentifierBuilder"
                      - "get{{ domainEntity }}CreateValidatorRules"
                      - "get{{ domainEntity }}CreateValidatorRulePlugins"
    - AddZedBusinessFactoryMethod:
          arguments:
              factoryMethod:
                  value: "get{{ domainEntity }}CreateValidatorRules"
              interfaceName:
                  value: "\\{{ organization }}\\Zed\\{{ module }}\\Business\\{{ domainEntity }}\\Validator\\{{ domainEntity }}ValidatorRuleInterface[]"
              body:
                  value: "return [];"
    - AddZedBusinessFactoryMethod:
          arguments:
              factoryMethod:
                  value: "create{{ domainEntity }}UpdateValidator"
              className:
                  value: "{{ domainEntity }}Validator"
              interfaceName:
                  value: "\\{{ organization }}\\Zed\\{{ module }}\\Business\\{{ domainEntity }}\\Validator\\{{ domainEntity }}ValidatorInterface"
              subDirectory:
                  value: "{{ domainEntity }}/Validator"
              dependencyMethods:
                  value:
                      - "get{{ domainEntity }}IdentifierBuilder"
                      - "get{{ domainEntity }}UpdateValidatorRules"
                      - "get{{ domainEntity }}UpdateValidatorRulePlugins"
    - AddZedBusinessFactoryMethod:
          arguments:
              factoryMethod:
                  value: "get{{ domainEntity }}UpdateValidatorRules"
              interfaceName:
                  value: "\\{{ organization }}\\Zed\\{{ module }}\\Business\\{{ domainEntity }}\\Validator\\{{ domainEntity }}ValidatorRuleInterface[]"
              body:
                  value: "return [];"
