spryk: schemaProperty
description: "Adds a Persistence schema to *module*.schema.xml in the Zed application."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    propertyName: ~

    propertyType: ~

    required: ~

    autoIncrement: ~

    primaryKey: ~

    defaultValue: ~

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Persistence/Propel/Schema/spy_{{ module | underscored }}.schema.xml"

preSpryks:
    - AddZedPersistencePropelSchemaTable:
          arguments:
              tableName:
                  value: "spy_{{ module | underscored }}"
              targetModule:
                  value: "{{ module | underscored }}"
